apiVersion: v2
appVersion: "2020.03"
description: BDBA Helm chart
name: bdba
version: 1.0
dependencies:
- name: postgresql
  version: "6.5.8"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: minio
  version: "5.0.16"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: memcached
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: "3.1.0"
- name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: "6.17.0"
