apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bdba.fullname" . }}-beat
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bdba.name" . }}-beat
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "bdba.name" . }}-beat
      labels:
        app.kubernetes.io/name: {{ include "bdba.name" . }}-beat
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name | quote }}
      annotations:
        {{- include "bdba.configchecksum" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-beat
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          args: [ "beat" ]
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/celerybeat.pid
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/celerybeat.pid
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
          {{- include "bdba.frontendenv" . | nindent 10 }}
          volumeMounts:
          {{- include "bdba.frontendmounts" . | indent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      volumes:
      {{- include "bdba.frontendvolumes" . | indent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
