apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bdba.fullname" . }}-services-configmap
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
data:
  {{- if .Values.postgresql.enabled }}
  PGUSER: {{ .Values.postgresql.postgresqlUsername }}
  {{- if .Values.postgresql.postgresqlPort }}
  PGPORT: {{ .Values.postgresql.postgresqlPort }}
  {{- end }}
  PGDATABASE: {{ .Values.postgresql.postgresqlDatabase }}
  PGHOST: {{ template "bdba.postgresql.fullname" . }}
  {{- else }}
  PGUSER: {{ .Values.frontend.database.postgresqlUsername }}
  {{- if .Values.frontend.database.postgresqlPort }}
  PGPORT: {{ .Values.frontend.database.postgresqlPort }}
  {{- end }}
  PGDATABASE: {{ .Values.frontend.database.postgresqlDatabase }}
  PGHOST: {{ .Values.frontend.database.postgresqlHost }}
  {{- if .Values.frontend.database.postgresqlSslMode }}
  PGSSLMODE: {{ .Values.frontend.database.postgresqlSslMode }}
  {{- end }}
  {{- if .Values.frontend.database.clientSecretName }}
  PGSSLKEY: "/postgresql/client-cert/tls.key"
  PGSSLCERT: "/postgresql/client-cert/tls.crt"
  {{- end }}
  {{- if .Values.frontend.database.rootCASecretName }}
  PGSSLROOTCERT: "/postgresql/ca/ca.pem"
  {{- end }}
  {{- end }}
  S3_ENDPOINT: "http://{{ template "bdba.minio.fullname" . }}:{{ .Values.minio.service.port }}"
  MEMCACHED: "{{ template "bdba.memcached.fullname" . }}:11211"
  BROKER_URL: "{{ template "bdba.rabbitmq.brokerUrl" . }}"