{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bdba.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "bdba.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ $fullName }}-webapp
                port:
                  number: 8000
        {{- else }}
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}-webapp
              servicePort: 8000
        {{- end }}
  {{- end }}
