{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bdba.fullname" . -}}
apiVersion: extensions/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "bdba.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}-webapp
              servicePort: 8000
{{- end }}
