{{- if not .Values.frontend.web.secretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-django-secrets-generated
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ include "bdba.generated.djangoSecretKey" . | b64enc | quote }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-django-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.frontend.web.secretKey | b64enc | quote }}
{{- end }}
