apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bdba.fullname" . }}-manage-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
  name: {{ include "bdba.fullname" . }}-manage-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
  name: {{ include "bdba.fullname" . }}-bdba-manage-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bdba.fullname" . }}-manage-secrets
subjects:
- kind: ServiceAccount
  name: {{ include "bdba.fullname" . }}-manage-secrets
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
  name: {{ include "bdba.releaseversion" . }}-secret-init
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  template:
    metadata:
      labels:
        app: {{ template "bdba.name" . }}
        chart: {{ template "bdba.chart" . }}
        release: {{ .Release.Name }}
      name: {{ include "bdba.releaseversion" . }}-secret-init
    spec:
      containers:
        - name: {{ .Chart.Name }}-webapp
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          args: [ "make-secrets", "{{ .Release.Namespace }}" ]
      restartPolicy: OnFailure
      serviceAccount: {{ include "bdba.fullname" . }}-manage-secrets
