{{- if .Values.frontend.createSecrets }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
  name: {{ include "bdba.releaseversion" . }}-secret-init
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  template:
    metadata:
      labels:
        app: {{ template "bdba.name" . }}
        chart: {{ template "bdba.chart" . }}
        release: {{ .Release.Name }}
      name: {{ include "bdba.releaseversion" . }}-secret-init
    spec:
      containers:
        - name: {{ .Chart.Name }}-webapp
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          args: [ "make-secrets", "{{ .Release.Namespace }}" ]
          env:
            - name: BROKER_URL_TEMPLATE
              value: "{{ template "bdba.rabbitmq.brokerUrl" . }}"
      restartPolicy: OnFailure
      serviceAccount: {{ template "bdba.frontend.serviceAccountName" . }}
{{- end }}
