{{- if not .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-rabbitmq-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.brokerUrl }}
  BROKER_URL: {{ .Values.brokerUrl | b64enc | quote }}
  {{- end }}
{{- end }}
