{{- if and .Values.postgresql.enabled }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-postgresql-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.frontend.database.postgresqlPassword }}
  PGPASSWORD: {{ .Values.frontend.database.postgresqlPassword | b64enc | quote }}
  {{- end }}
{{- end }}
