{{- if .Values.worker.applicationLogging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
  labels:
{{ include "bdba.labels" . | indent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon       Off
        Flush        5
        Log_Level    info
        HTTP_Server  Off
        Parsers_File /bdba-fluentbit/parsers.conf

    [INPUT]
        Name         tail
        Tag          worker
        Path         /app-log/celery.log
        Parser       json
        DB           /app-log/celery.db

    [FILTER]
        Name record_modifier
        Match *
        Record hostname ${HOSTNAME}

    [OUTPUT]
        Name         forward
        Match        *
        Host         {{ template "bdba.fluentd.fullname" . }}

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L

---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bdba.fullname" . }}-worker
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bdba.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "bdba.name" . }}-worker
      labels:
        app.kubernetes.io/name: {{ include "bdba.name" . }}-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-user.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.worker.repository }}:{{ .Values.worker.tag }}"
          imagePullPolicy: {{ .Values.worker.pullPolicy }}
          readinessProbe:
            exec:
              command: ["/docker-healthcheck.sh" ]
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["/docker-healthcheck.sh" ]
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ mul .Values.worker.concurrency 250 }}m
              memory: {{ mul .Values.worker.concurrency .Values.worker.memoryPerScanner }}Gi
              ephemeral-storage: {{ mul .Values.worker.concurrency .Values.worker.storagePerScanner}}Gi
            limits:
              cpu: {{ mul .Values.worker.concurrency 2 }}
              memory: {{ mul .Values.worker.concurrency 6}}Gi
              ephemeral-storage: {{ mul .Values.worker.concurrency 100}}Gi
          {{- include "bdba.workerenv" . | nindent 10 }}
          volumeMounts:
            - name: {{ include "bdba.fullname" . }}-worker-applog
              mountPath: /app-log
            - name:  {{ include "bdba.fullname" . }}-worker-tmp
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
        {{- if .Values.worker.applicationLogging.enabled }}
        - name: {{ .Chart.Name }}-worker-fluentbit
          image: "{{ .Values.fluentbit.repository }}:{{ .Values.fluentbit.tag }}"
          imagePullPolicy: {{ .Values.fluentbit.pullPolicy }}
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/bdba-fluentbit/fluent-bit.conf"]
          volumeMounts:
            - name:  {{ include "bdba.fullname" . }}-worker-applog
              mountPath: /app-log
            - name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
              mountPath: /bdba-fluentbit/
        {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      volumes:
      - name: {{ include "bdba.fullname" . }}-worker-applog
        emptyDir: {}
      - name: {{ include "bdba.fullname" . }}-worker-tmp
        emptyDir: {}
      {{- if .Values.worker.applicationLogging.enabled }}
      - name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
        configMap:
          name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "bdba.name" . }}-worker
              topologyKey: "kubernetes.io/hostname"
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: rabbitmq
              topologyKey: "kubernetes.io/hostname"
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: postgresql
              topologyKey: "kubernetes.io/hostname"
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: minio
              topologyKey: "kubernetes.io/hostname"
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
